[workspace]
description = "A Mojo implementation of the Python zlib library, providing compression, decompression, and checksum functionality. This library offers a Python-compatible API for zlib operations in Mojo, enabling seamless migration from Python code."
authors = ["gabrieldemarmiesse <gabrieldemarmiesse@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://prefix.dev/pixi-build-backends"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/gabrieldemarmiesse/mojo-zlib"
repository = "https://github.com/gabrieldemarmiesse/mojo-zlib"
preview = ["pixi-build"]

[tasks]
test = "mojo test -I ./src"
test-all = "python scripts/test.py"
format = "mojo format"

[dependencies]
mojo = ">=25.3.0.dev2025042605"
zlib = ">=1.3.1"

[package]
name = "mojo-zlib"
version = "0.1.6"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[feature.util.dependencies]
typer = ">=0.16.0,<0.17"
pyyaml = ">=6.0.2,<7"

[feature.util.tasks]
publish = "python scripts/publish.py build-and-publish"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }

